runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

